### PR TITLE
Allow specifying target version

### PR DESCRIPTION
**Pull request by arvindsv**
Does this:

1. Updates README: Mostly Go => GoCD and *.go.cd to *.gocd.org.
2. Accept multiple patterns in the settings file. Old (single) patterns work too.
3. Allow specifying target version in the JSON. The field I chose is "version".

It'll be like this:

```
{
  "format_version": 2,
  "name": "pipeline1",
  ...
}
```

```
{
  "format_version": 2,
  "name": "environment1",
  ...
}
```

~~I can change "version" to something else, if you prefer. "json_version"? "file_version"? I don't want people to confuse it with some kind of a version for the pipeline/environment.~~

Edit: Based on @tomzo's comment below, this has been changed to `format_version`.

### CODE REVIEW

**Comment by tomzo** [comment]
> I can change "version" to something else, if you prefer. "json_version"? "file_version"? I don't want people to confuse it with some kind of a version for the pipeline/environment.

I think `format_version` would be clearer. Same in yaml.

**Comment by arvindsv** [comment]
@tomzo This is done. Changed it to `format_version`. Tested it too - and it looks ok. Even the multiple pattern part. I'll do something similar for yaml too.

**Comment by arvindsv** [comment]
Errors show like this:





Not pretty, but descriptive.

**Comment by arvindsv** [comment]
I haven't changed the README to explain the concept of `format_version` and that you need to use `lock_behavior` instead of `enable_pipeline_locking`. I'll leave that to you, if that's ok.

**Comment by tomzo** [comment]
OK, I'll merge this and update the readme. I presume `lock_behavior` will be since 17.11

**Comment by arvindsv** [comment]
It will be in 17.12 (November), actually. Won't make it to 17.11 (this week). So, it's not urgent, but this change should be alright to merge at any time.

**Comment by tomzo** [comment]
I have merged this and released with `0.2.1`. When you are done with yaml, I will make a release there too. Then I will submit PR for bumping bundled versions.

**Comment by arvindsv** [comment]
Just for the record, the corresponding PR in the GoCD codebase is https://github.com/gocd/gocd/pull/3943.

**Pull request merged**
