### PR TITLE
Adding Pipeline Export endpoint

### PR DESCRIPTION
**Pull request by ibnc**
This PR implements the plugin side of https://github.com/gocd/gocd/pull/5330

### CODE REVIEW

**Comment by ibnc** [comment]
Related to: https://github.com/gocd/gocd/issues/5175

**Comment by tomzo** [comment]
I had to rebase this, but it's merged now.

**Comment by arvindsv** [comment]
@ketan brought this up. It looks like the changes from this PR are not merged in. Maybe the rebase went wrong?

**Comment by tomzo** [comment]
Yes, I screwed something up.
Fixed now and forced pushed new tags, release and new jar.

**Pull request closed without merging**
