### PR TITLE
Plugin CLI should accept STDIN input for syntax check

### PR DESCRIPTION
**Pull request by marques-work**
Make this CLI well-behaved like other userland tools (i.e., accept piped STDIN). To use this, specify "-" as the input file and connect with a shell pipe character.

### CODE REVIEW

**Comment by marques-work** [comment]
@tomzo this should be a safe change. The changeset is bigger than expected because I renamed `JsonFileParser` to `JsonConfigParser` (as it can now parse a generic `InputStream` rather than just a `File`).

**Comment by marques-work** [comment]
@tomzo FYI - the caller/consumer of this plugin's CLI is https://github.com/gocd-contrib/gocd-cli

**Comment by tomzo** [comment]
Thanks. I saw your project earlier, but it was non-functional then I guess.
If it is ready, perhaps it would be nice to add readme here or a link at least?

**Comment by marques-work** [comment]
@tomzo I can do that -- currently, it's not ready for release (needs to implement more functionality), but is functional. I need to add some docs to the gocd-cli project

**Comment by marques-work** [comment]
@tomzo added some documentation on how to build the gocd-cli and use it with the plugin (some of the docs on are the gocd-cli page)

**Pull request merged**
