### PR TITLE
Adding CR Contract dependency, and use for export

### PR DESCRIPTION
**Pull request by ibnc**
This should not be merged until 19.1.0 is merged as the contract won't be released until then. The `goCdVersion` will also need to be updated to 19.1.0

You can test these changes by changing the dependencies to:

```
compileOnly group: 'cd.go.plugin', name: 'go-plugin-config-repo-experimental', version: "19.1.0-8395"
testCompile group: 'cd.go.plugin', name: 'go-plugin-config-repo-experimental', version: "19.1.0-8395"
```

@marques-work @kierarad Feel free to pull this to test if it fixes the issue talked about here: https://github.com/gocd/gocd/issues/5688#issuecomment-454220314

### CODE REVIEW

**Comment by arvindsv** [comment]
One scenario comes to mind: What happens if the `format_version` is not up to date? Old versions work currently. Do they still work, after this change?

**Comment by tomzo** [comment]
> One scenario comes to mind: What happens if the format_version is not up to date? Old versions work currently. Do they still work, after this change?

I think this won't work now. Let's say there is config-repo with `format_version: 1` somewhere. If we try to parse with this change, then `enable_pipeline_locking: true` will not have a field on the CR classes. It will not be migrated neither to the v3 format.

My proposition is that if format_version is `current` (what plugin knows last) then we can parse with new method, using CR classes. In other cases, we should parse with the old style.
There is no alternative, unless you want to move migration code to the new module too. But that does not feel right to me.

**Comment by arvindsv** [comment]
> There is no alternative, unless you want to move migration code to the new module too. But that does not feel right to me.

Me neither. Then, every plugin will have to have similar migration code.

**Comment by ibnc** [comment]
@tomzo @arvindsv 
These are valid points that we need to consider for parse director and parse content. This PR only uses the contract for the export atm.

**Comment by tomzo** [comment]
@ibnc I believe that similar problem applies to the export. For example if plugin uses `go-plugin-config-repo` 19.1, then if that plugin is used on higher GoCD server (e.g. 19.6) then some JSON fields sent by gocd could mismatch the contract object onto which we are deserializing. 
What am trying to say here is that for json plugin, the safest approach for export is to return exactly the json which gocd has sent, because this will be always agnostic towards schema which particular gocd version uses.

**Comment by ibnc** [comment]
@tomzo Perhaps we should add a supported GoCD versions feature? Or enforce that the GoCD Server and the plugin are using the same version of go-plugin-config-repo?

**Comment by ibnc** [comment]
Or perhaps the server can tell the plugins what version it's using, and then the plugins install or reference it... idk, just spitballing 

Or we can start doing versioning of the contract? like the apis?

**Pull request closed without merging**
