### PR TITLE
Update & modernize build and dependencies

### PR DESCRIPTION
**Pull request by chadlwilson**
Same as https://github.com/tomzo/gocd-yaml-config-plugin/pull/158

- Upgrades to Gradle 7 incl. required plugin + compatibility changes
- Bumps all test dependencies to latest versions, along with required compatibility changes
- Bumps included dependencies to patched versions without published vulnerabilities

I've compared to built jar before-and-after and everything looks in tact. There are no changes to production code, but wanted to bump the version notably due to the dependency changes.

### CODE REVIEW

**Comment by chadlwilson** [comment]
Thanks! Are you able to please cut a release of this one too? 🙏

**Comment by chadlwilson** [comment]
@tomzo Friendly ping! Pretty please 😅

If you're interested in the draft release notes, you can take a look at https://github.com/gocd/www.go.cd/pull/1394 - mainly bugfix, patching and general maintenance as you can see :-)

**Comment by tomzo** [comment]
Hey Chad.

I've published the release.

Sorry, it took so long. I tried this on 2 different days and I was getting network errors downloading gradle.

Nice to see a new GoCD release, thanks for driving it :)

**Comment by chadlwilson** [comment]
Thank you thank you!

**Pull request merged**
